# Generated by Django 5.2.6 on 2025-09-04 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="User's email address", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(help_text="User's first name", max_length=100)),
                ('last_name', models.CharField(blank=True, help_text="User's last name (optional)", max_length=100)),
                ('company', models.CharField(blank=True, help_text='Company name (optional)', max_length=200)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20)),
                ('referral_source', models.CharField(blank=True, help_text='How did they hear about us?', max_length=100)),
                ('message', models.TextField(blank=True, help_text='Additional message from user')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level set by admin', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('contacted', 'Contacted')], default='pending', help_text='Current status', max_length=15)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the entry was last updated')),
                ('position', models.PositiveIntegerField(editable=False, help_text='Position in waitlist (auto-calculated)')),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
