# Generated by Django 5.2.6 on 2025-09-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistentry',
            name='company',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='message',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='referral_source',
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='role',
            field=models.CharField(blank=True, choices=[('freelancer', 'Freelancer'), ('manager', 'Manager'), ('student', 'Student'), ('business_owner', 'Business Owner')], help_text="User's role or use case (optional)", max_length=20),
        ),
    ]
